In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_salaries = df[pd.notna(df['salary_year_avg'])].copy()

In [3]:
def projected_salary(salary):
    return salary * 1.03

df_salaries['salary_year_inflated'] = df_salaries['salary_year_avg'].apply(projected_salary)

df_salaries[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [4]:
def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03

df_salaries['salary_year_inflated'] = df_salaries.apply(projected_salary, axis=1)

df_salaries[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]

In [5]:
import ast

ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [6]:

def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [7]:
df_salaries['salary_year_inflated'] = df.salary.apply(projected_salary, axis=1)

AttributeError: 'DataFrame' object has no attribute 'salary'